[package]
  name = "close-eyes"
  version = "0.1.0"
  edition = "2024"

[dependencies]
  serde = { version = "1.0.219", features = ["derive"] }
  notify-rust = "4.11.7"
  rfd = "0.15.3"
  tokio = { version = "1.44.2", features = ["full"] }
  serde_json = "1.0.140"
