set dotenv-load := false

# Simple variables
BINARY := "json-compare-cli"
PREFIX := "/usr/local/bin"

default:
    @echo "usage: just [command]"

help:
    just --list

lint:
    @echo "Checking code style..."
    cargo fmt -- --check
    cargo clippy -- -D warnings

test: lint
    @echo "Running tests..."
    cargo test

build: test
    cargo build --release
    @echo "Built {{BINARY}} in target/release/"

install: build
    sudo cp target/release/{{BINARY}} {{PREFIX}}/
    @echo "Installed {{BINARY}} to {{PREFIX}}/"

uninstall:
    sudo rm -f {{PREFIX}}/{{BINARY}}
    @echo "Uninstalled {{BINARY}} from {{PREFIX}}/"

clean:
    cargo clean
    @echo "Cleaned build artifacts."

publish: test
    @echo "Publishing to crates.io..."
    cargo publish
